# Generated by Django 5.0.2 on 2024-03-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_autor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autor",
            name="url",
        ),
    ]
